### ISSUE TITLE
.tiff cover images don't load

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#482]
^ title
![image](https://github.com/digimezzo/dopamine/assets/148219987/f872dc92-e171-4183-a6a3-836c85705908)

**Comment by digimezzo** [comment]
Tiff is currently not supported, but I can add that. Where are these tiff images located (in relation to the audio files) and what are the file names?

**Comment by DopamineUser** [comment]
Cover.tiff
Embedded within audio file

**Comment by digimezzo** [comment]
Could you share one of those files? I'd like to test this out.

**Comment by DopamineUser** [comment]
[TestFiles.zip](https://github.com/digimezzo/dopamine/files/13334627/TestFiles.zip)

**Comment by digimezzo** [comment]
@DopamineUser Did you test this with preview 25 https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.25 also? It has an extra fix for images compared to the nighty that you tested.

**Comment by DopamineUser** [comment]
> @DopamineUser Did you test this with preview 25 https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.25 also? It has an extra fix for images compared to the nighty that you tested.

just tried installing it and got this
![image](https://github.com/digimezzo/dopamine/assets/148219987/b1ea387a-d8c9-499d-8932-9596604d5a49)
re-downloaded and the same thing happened

**Comment by digimezzo** [comment]
@DopamineUser Wow that's not good. I have it too here and am trying to find out what went wrong.

**Comment by digimezzo** [comment]
@DopamineUser Should be fixed now. I re-uploaded the Windows package, downloaded it and launched it and it works here now. It must have been an upload problem.

**Comment by DopamineUser** [comment]
> @DopamineUser Did you test this with preview 25 https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.25 also? It has an extra fix for images compared to the nighty that you tested.

![image](https://github.com/digimezzo/dopamine/assets/148219987/dc3f6f30-8653-4d44-b9ba-a5a6daa87a87)
sadly no difference

**Comment by digimezzo** [comment]
@DopamineUser I'm fixing that for you. You can expect a nightly with the fix in a few hours.

**Comment by digimezzo** [comment]
@DopamineUser Your nightly is ready: https://github.com/digimezzo/dopamine/actions/runs/8131733170

**Comment by DopamineUser** [comment]
> @DopamineUser Your nightly is ready: https://github.com/digimezzo/dopamine/actions/runs/8131733170

thanks :) works now

also there's a bug you missed: after launching dopamine, playing something and then opening the now playing screen for the first time, it says no track is currently playing.

**Comment by digimezzo** [comment]
@DopamineUser This nightly fixes the now playing issue: https://github.com/digimezzo/dopamine/actions/runs/8132923641

**Comment by digimezzo** [comment]
Tiff is proably broken again due to fixing issue #633. I had no other option. This will be looked at later.
